name: ESP32 Anolex Controller 3030 Max by Axo
board: ESP32 Anolex Controller
stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 0
  pulse_us: 3
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: gpio.21:low
  homing_runs: 2
  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 150
    max_travel_mm: 285
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 800
      feed_mm_per_min: 25
    motor0:
      limit_all_pin: gpio.36:low
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        direction_pin: gpio.15
        step_pin: gpio.13
        disable_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 150
    max_travel_mm: 290
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: true
      seek_mm_per_min: 800
      feed_mm_per_min: 25
    motor0:
      limit_all_pin: gpio.39:low
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        direction_pin: gpio.27:low
        step_pin: gpio.14
        disable_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 150
    max_travel_mm: 68
    soft_limits: true
    homing:
      cycle: 1
      mpos_mm: 0
      positive_direction: true
      seek_mm_per_min: 800
      feed_mm_per_min: 25
    motor0:
      limit_all_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        direction_pin: gpio.25
        step_pin: gpio.26
        disable_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
  a:
    steps_per_mm: 100
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 300
    soft_limits: true
    homing:
      cycle: -1
      mpos_mm: 0
      positive_direction: true
      seek_mm_per_min: 800
      feed_mm_per_min: 25
    motor0:
      limit_all_pin: gpio.4:pu:low
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        direction_pin: gpio.32
        step_pin: gpio.33
        disable_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
PWM:
  output_pin: gpio.17
  disable_with_s0: false
  off_on_alarm: true
  speed_map: 0=0.000% 100=0.000% 10000=100.000%
  enable_pin: NO_PIN
  direction_pin: NO_PIN
  s0_with_disable: true
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: gpio.35
coolant:
  flood_pin: gpio.16
  mist_pin: gpio.22
probe:
  pin: gpio.12:low:pu
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: gpio.2:pu:low
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN
  homing_button_pin: NO_PIN
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.01
verbose_errors: true
start:
  check_limits: true
macros:
  macro0: $H
